# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: jest-test
        run: cross-env NODE_OPTIONS=--experimental-vm-modules npx jest
        
      - name: linter-test
        run: make lint
